### ISSUE TITLE
Ethernet

### ISSUE THREAD

**Issue by nottledim** [DitroniX/IPEM-IoT-Power-Energy-Monitor#2]
Very interesting board. I built a similar thing a couple of years ago. The main problem I have is the dependence on WiFi. WiFi is not particularly reliable and should probably be avoided if possible for "infrastructure" devices. I suspect it's too late but you should consider incorporating an Ethernet connection.

**Comment by DitroniX** [comment]
Hi @nottledim , been so busy past weeks that I appear to gave missed your comment, apologies.

You make a very valid point and this has also been fed back from a couple of other users for the GTEM board.

What I have done, is to currently make two IPEM versions of the ESP32.  With internal PCB Antenna, and the other with the IPX U.FL connector to allow an external antenna - as highted below.

- **ESP32-WROOM-32E-N4**
  - Integral Antenna 
  - Wireless and Bluetooth
- **ESP32-WROOM-32UE-N4**
  - Ext Antenna - U.FL Socket
  - Wireless and Bluetooth

This hopefully will help those whom have a problem with WLAN signal, or mount the board inside a metal enclosure (such as a consumer unit).  The U.FL connector can now be easily extended to an external antenna mounted on an enclosure, or further away.  If using a longer coax cable, it maybe required to use a higher gain antenna, so make up the feeder losses.  This works well.

Going back to your ethernet question directly, I will investigate this option next - GPIO ports will need consideration.   As the board can be powered via the AC input, so fortunately PoE should not be required.

Keep you posted!
Regards
Dave

**Comment by DitroniX** [comment]
Placeholder for this Ethernet Project added https://github.com/DitroniX/EPEM-Ethernet-Power-Energy-Monitor

**Comment by DitroniX** [comment]
Valued feedback which has been noted as a potential future project.
